name: learning-merge-queue
run-name: ${{ github.actor }} is learning merge queue

on:
  pull_request:
    types: [opened]
    branches: [main]
  merge_group:
    types: [checks_requested]
    branches: [main]
  push:
    branches: [main]

jobs:
  job_a:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: github.event_name == 'pull_request'
    steps:
      - run: |
          echo "プルリクエストのときだけ実行されるやつ"
          echo "github.ref='${{ github.ref }}'"
          echo "github.sha='${{ github.sha }}'"

  job_b:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: github.event_name == 'merge_group'
    steps:
      - run: |
          echo "マージキューのときだけ実行されるやつ"
          echo "github.ref='${{ github.ref }}'"
          echo "github.sha='${{ github.sha }}'"

  job_c:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: github.event_name == 'push'
    steps:
      - run: |
          echo "プッシュのときだけ実行されるやつ"
          echo "github.ref='${{ github.ref }}'"
          echo "github.sha='${{ github.sha }}'"

  job_d:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: |
          echo "いつでも実行されるやつ"
          echo "github.ref='${{ github.ref }}'"
          echo "github.sha='${{ github.sha }}'"

  job_status:
    runs-on: ubuntu-latest
    needs: [job_a, job_b, job_c, job_d]
    if: ${{ !cancelled() && !failure() }}
    steps:
      - run: |
          echo "ステータスチェックOK"
